name: Docker Build and Push matvey-3000 image

on:
  push:
    tags:
      - '*'  # Build and push for all new tags
  workflow_dispatch:

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

      - name: Get Git SHA
        id: git_sha
        run: echo "sha=$(git describe --tags)" >> $GITHUB_OUTPUT

      - name: Login to Github Packages
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT }}

      - name: Build image and push to Github Registry
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./docker/bot.Dockerfile
          tags:
            ghcr.io/shrimpsizemoose/matvey-3000:${{ steps.git_sha.outputs.sha }}
          push: true

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}

